/**
 * Versions
 */

internal const val VERSION_AGP = "8.2.0"
internal const val VERSION_KOTLIN = "1.9.0"
internal const val VERSION_CORE_KTX = "1.10.1"
internal const val VERSION_APP_COMPAT = "1.6.1"
internal const val VERSION_ANDROID_MATERIAL = "1.11.0"
internal const val VERSION_LIFE_CYCLE_KTX = "2.6.1"
internal const val VERSION_COMPOSE = "1.7.0"
internal const val VERSION_COMPOSE_BOM = "2023.08.00"
internal const val VERSION_JUNIT = "4.13.2"
internal const val VERSION_ANDROID_EXT_JUNIT = "1.1.5"
internal const val VERSION_ANDROID_ESPRESSO_CORE = "3.5.1"
internal const val VERSION_ANDROID_COMPOSE_BOM = "2023.08.00"
internal const val VERSION_COMPOSE_SDP = "1.1.0"
internal const val VERSION_APOLLO_PLUGIN = "3.8.2"
internal const val VERSION_APOLLO = "3.8.2"
internal const val HILT_VERSION = "2.48"
internal const val PAGING_VERSION = "3.2.1"
internal const val VIEW_MODEL_COMPOSE_VERSION = "2.6.2"
internal const val SWIPE_REFRESH_VERSION = "0.27.0"
internal const val COMPOSE_NAVIGATION_VERSION = "2.7.6"
internal const val OK_HTTP_INTERCEPTOR_VERSION = "4.9.0"
internal const val CORE_TESTING_VERSION = "2.1.0"
internal const val COROUTINE_TESTING_VERSION = "1.6.2"
internal const val MOCKITO_VERSION = "4.6.1"
internal const val MOCKITO_KOTLIN_VERSION = "1.6.0"